In [1]:
import numpy as np
import pandas as pd
from scipy.linalg import block_diag

In [2]:
def remove_s(s_num):
    return int(s_num[1:])

In [5]:
canvas_df = (pd.read_csv("./data/canvas.csv", names=["s_number"])).applymap(remove_s)
canvas_df = canvas_df.astype({"s_number":np.int})
# print(canvas_df.head())
# print(canvas_df.count())

In [6]:
data_type_dict = {"s_number":np.int, "house":np.str, "do_group":np.str}

In [7]:
house_df = pd.read_csv("./data/houses.csv", names=list(data_type_dict.keys())).drop_duplicates()
house_df = house_df[~house_df["s_number"].isna()]
house_df = house_df.astype(data_type_dict)

In [8]:
s_numbers = list(canvas_df["s_number"])
student_house_df = house_df[house_df["s_number"].isin(s_numbers)]
# print(student_house_df.count())

In [9]:
rogue_house = ["GUEST", "nan"]

do_group_df = student_house_df[student_house_df["do_group"] != "nan"]
house_df = student_house_df[~student_house_df["house"].isin(rogue_house)]
others_df = student_house_df[student_house_df["house"].isin(rogue_house)]

# print(do_group_df.head(), "\n", do_group_df.count(), end="\n")
# print(house_df.head(), "\n", house_df.count(), end="\n")
# print(others_df.head(), "\n", others_df.count(), end="\n")

In [10]:
houses = house_df["house"].unique()
do_groups = do_group_df["do_group"].unique()

# print(houses)
# print(do_groups)

In [17]:
def rotate(arr):
    return np.append([arr[-1]], arr[0:-1])

In [18]:
def gen_matrix(in_df, index, name):
    matrix = np.zeros((0,0), dtype = np.int)
    for iterator in index:
        part_of_df = in_df[in_df[name] == iterator]
        count = part_of_df.shape[0]
        size = (count, count)
        sub_matrix = np.zeros(size, dtype=np.int)
        
        connecting_array = np.arange(2, min(count, 9))
        np.random.shuffle(connecting_array)
        connecting_array = np.concatenate(([1], connecting_array))
        
        for i in range(0, min(count, 8)):
            sub_matrix[i]
#             np.fill_diagonal(sub_matrix[:, (i+1):], connecting_array)
#             connecting_array = rotate(connecting_array)
        
        matrix = block_diag(matrix, sub_matrix)
    return matrix
do_group_connections = gen_matrix(do_group_df, do_groups, "do_group")
house_connections = gen_matrix(house_df, houses, "house")

In [20]:
print(do_group_connections[0:11, 0:11])
print(do_group_connections[11:24, 11:24])

[[0 1 7 6 3 5 8 2 4 0 0]
 [0 0 4 1 7 6 3 5 8 2 0]
 [0 0 0 2 4 1 7 6 3 5 8]
 [0 0 0 0 8 2 4 1 7 6 3]
 [0 0 0 0 0 5 8 2 4 1 7]
 [0 0 0 0 0 0 3 5 8 2 4]
 [0 0 0 0 0 0 0 6 3 5 8]
 [0 0 0 0 0 0 0 0 7 6 3]
 [0 0 0 0 0 0 0 0 0 1 7]
 [0 0 0 0 0 0 0 0 0 0 4]
 [0 0 0 0 0 0 0 0 0 0 0]]
[[0 1 4 7 8 3 5 2 6 0 0 0 0]
 [0 0 6 1 4 7 8 3 5 2 0 0 0]
 [0 0 0 2 6 1 4 7 8 3 5 0 0]
 [0 0 0 0 5 2 6 1 4 7 8 3 0]
 [0 0 0 0 0 3 5 2 6 1 4 7 8]
 [0 0 0 0 0 0 8 3 5 2 6 1 4]
 [0 0 0 0 0 0 0 7 8 3 5 2 6]
 [0 0 0 0 0 0 0 0 4 7 8 3 5]
 [0 0 0 0 0 0 0 0 0 1 4 7 8]
 [0 0 0 0 0 0 0 0 0 0 6 1 4]
 [0 0 0 0 0 0 0 0 0 0 0 2 6]
 [0 0 0 0 0 0 0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]
